# TODO: Detect libraries automatically
# * Neither ldd not ntldd seem to provide quite the right list?

DLLS = [
    "libcairo-gobject-2.dll",
    "libcairo-2.dll",
    "libgdk-3-0.dll",
    "libgdk_pixbuf-2.0-0.dll",
    "libgio-2.0-0.dll",
    "libgobject-2.0-0.dll",
    "libglib-2.0-0.dll",
    "libgtk-3-0.dll",
    "libpango-1.0-0.dll",
    "libgcc_s_dw2-1.dll",
    "libssp-0.dll",
    "libfontconfig-1.dll",
    "libfreetype-6.dll",
    "libpixman-1-0.dll",
    "libpng16-16.dll",
    "zlib1.dll",
    "libepoxy-0.dll",
    "libfribidi-0.dll",
    "libintl-8.dll",
    "libgmodule-2.0-0.dll",
    "libffi-7.dll",
    "libpangocairo-1.0-0.dll",
    "libpangowin32-1.0-0.dll",
    "libwinpthread-1.dll",
    "libpcre-1.dll",
    "libatk-1.0-0.dll",
    "libharfbuzz-0.dll",
    "libthai-0.dll",
    "libpangoft2-1.0-0.dll",
    "libexpat-1.dll",
    "libiconv-2.dll",
    "libbrotlidec.dll",
    "libbz2-1.dll",
    "libgraphite2.dll",
    "libdatrie-1.dll",
    "libbrotlicommon.dll",
    "libstdc++-6.dll",
]

with open('libraries.wxi', 'w') as f:
    f.write("<!-- Generated by libraries-wxi-gen.py -->\n")
    f.write('<Include>\n')

    for i in DLLS:
        id_ = i.replace('.dll', '').replace('-', '_').replace('+', '')
        #print(7 * 4 * ' ' + f"<File Id='{id_}' Name='{i}' DiskId='1' Source='out/{i}' />")
        f.write(f"    <File Name='{i}' DiskId='1' Source='out/{i}' />\n")


    f.write('</Include>\n')
