import re
import subprocess

NTLDD = '/mingw32/bin/ntldd.exe'
DLL_RE = r"c:\\msys64\\mingw32\\bin\\(\S+.dll)"
EXES = {
    '../target/release/examples/keyboard_color.exe',
}

def find_depends(exe):
    output = subprocess.check_output([NTLDD, '-R', exe], universal_newlines=True)
    dlls = set()
    for l in output.splitlines():
        m = re.search(DLL_RE, l, re.IGNORECASE)
        if m:
            dlls.add(m.group(1))
    return dlls

dlls = set()
for i in EXES:
    dlls.union(find_depends(i))

with open('libraries.wxi', 'w') as f:
    f.write("<!-- Generated by libraries-wxi-gen.py -->\n")
    f.write('<Include>\n')

    for i in dlls:
        id_ = i.replace('.dll', '').replace('-', '_').replace('+', '')
        f.write(f"    <File Name='{i}' DiskId='1' Source='out/{i}' />\n")

    f.write('</Include>\n')